settings:
  title: 'PTU Status Page'
  url: '' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-ptu-edu-cn # unique identifier
    name: WWW
    description: 'Main Sites' # default=empty
    url: 'https://www.ptu.edu.cn/index.htm' # URL to fetch
    method: HEAD # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: news-ptu-edu-cn
    name: News
    description: 'Putian University News'
    url: 'https://news.ptu.edu.cn/'
    method: HEAD
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: oss-ptu-edu-cn
    name: OSS
    description: 'One-stop service platform'
    url: 'http://oss.ptu.edu.cn/'
    method: HEAD
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: mail-ptu-edu-cn
    name: Mail
    description: 'Mail Server'
    url: 'https://mail.ptu.edu.cn/'
    method: HEAD
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: pay-ptu-edu-cn
    name: Pay
    description: 'Payment platform'
    url: 'http://oss.ptu.edu.cn/'
    method: HEAD
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
