settings:
  title: 'PTU Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-ptu-edu-cn # unique identifier
    name: WWW
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.ptu.edu.cn/' # URL to fetch
    method: HEAD # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: news-ptu-edu-cn
    name: News
    description: 'News Server'
    url: 'https://www.cloudflare.com/'
    method: HEAD
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: oss-ptu-edu-cn
    name: OSSO
    url: 'http://oss.ptu.edu.cn/'
    method: HEAD
    expectStatus: 200
